ALTER TABLE locations ADD COLUMN term_bin TEXT NOT NULL DEFAULT '';
ALTER TABLE locations ADD COLUMN term_location TEXT NOT NULL DEFAULT '';
ALTER TABLE locations ADD COLUMN term_area TEXT NOT NULL DEFAULT '';
